### ISSUE TITLE
Log::warning() context not visible in Bugsnag

### ISSUE THREAD

**Issue by bkuhl** [bugsnag/bugsnag-laravel#315]
<img width="477" alt="screen shot 2018-08-28 at 8 12 16 pm" src="https://user-images.githubusercontent.com/524933/44757754-b7640280-aafe-11e8-920b-4c6ff8c993bc.png">

### Expected behavior
Passing a 2nd parameter (as context) to `Log::warning()` should append the log data similiar to `Bugsnag::addMetadata()` in that "Log Context" would appear as its own tab.

### Observed behavior
The data is not visible anywhere at all

### Steps to reproduce
I think the screenshot covers this pretty well

### Version
v3.14.1

**Comment by GrahamCampbell** [comment]
Interesting. You should be seeing the release tab there, since the context is directly used as metadata: https://github.com/bugsnag/bugsnag-psr-logger/blob/v1.4.1/src/BugsnagLogger.php#L110. I wonder if the word `release` is reserved, I'd have to dig into the code. Could you try using something other that "release" - does that work correctly?

**Comment by Cawllec** [comment]
Hi @bkuhl, I'm going to close this for now, but if you have an update or any further progress on the issue please let us know.
