### ISSUE TITLE
Oauth2 now throws 400 Bad Request and that reports to BugsNag

### ISSUE THREAD

**Issue by SagarNaliyapara** [bugsnag/bugsnag-laravel#400]
### Description
* The league/oauth2-server 8.0 upgrade now throws 400 Bad Request instead of the previous 401 Unauthorized.

This is currently not handled gracefully bubbles up to bugsnag.

### Expected behavior
* No error on bugsnag

### Observed behavior
* Bugsnag throwing error

### Steps to reproduce
* try to get a bearer token with incorrect login details.

This repo will log the error when running the curl command in the README

https://github.com/patrickomeara/passport_error

* I get a proper response back from the API when I test with the steps provided in the readme of above repository. but that still reports an error in BugsNag.

### Version
- Passport Version: 8.0.0
- Laravel Version: 6.5.0
- PHP Version: 7.3.11
- Database Driver & Version: Mysql 8.0.16

**Comment by mattdyoung** [comment]
Bugsnag captures all unhandled errors by design.

To prevent this being reported to Bugsnag you have a few options:
- catch and handle the error
- Add the error class to a list of [ignored exceptions](https://docs.bugsnag.com/platforms/php/laravel/configuration-options/#ignored-exceptions)
- Register a callback to examine the Bugsnag `$report` object and return `false` for the the specific error:
https://docs.bugsnag.com/platforms/php/laravel/customizing-error-reports/#adding-callbacks
