### ISSUE TITLE
setMetaData doesn't clear between horizon jobs

### ISSUE THREAD

**Issue by jwadhams** [bugsnag/bugsnag-laravel#483]
### Describe the bug
leaveBreadcrumb seems to correctly isolate data between Laravel queued jobs processed with Horizon workers. I love it, but sometimes, especially with query logging turned on, important breadcrumbs from early in the job appear to be pushed out by later ones.

setMetaData looks like a better replacement, but the behavior I'm seeing suggests this can leak between jobs. 

### Steps to reproduce
Create a simple job to reproduce the problem:

```
<?php
declare(strict_types=1);

namespace App\Jobs;

use App\Facades\Bugsnag;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class MetaJob extends Job implements ShouldQueue
{
    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    protected $state = null;

    public function __construct(string $state)
    {
        $this->state = $state;
    }

    public function handle(): void
    {
        Bugsnag::setMetaData(['MetaJob' => ['state' => $this->state]]);
        Bugsnag::leaveBreadcrumb('MetaJob', 'manual', ['state' => $this->state]);

        $seconds = mt_rand(0, 5);
        sleep($seconds);

        if ($this->state === 'fail') {
            throw new \Exception('MetaJob was asked to fail');
        }
    }
}
```

Dispatch that job several times with different inputs (I dispatched from Tinker)
```
\App\Jobs\MetaJob::dispatch('fail');
\App\Jobs\MetaJob::dispatch('succeed');
\App\Jobs\MetaJob::dispatch('whatever');
\App\Jobs\MetaJob::dispatch('fail');
\App\Jobs\MetaJob::dispatch('explode');
\App\Jobs\MetaJob::dispatch('victory');
\App\Jobs\MetaJob::dispatch('fail');
\App\Jobs\MetaJob::dispatch('go shopping');
```

In BugSnag, the Breadcrumbs never "cross the streams" but the Metadata routinely do. Using `merge:true` in setMetaData` only means _one_ random status will be set, it doesn't guarantee the right one, because of the delay. (The delay in my real jobs is based on i/o)

![Screen Shot 2022-03-14 at 5 07 32 PM](https://user-images.githubusercontent.com/1613739/158269111-1ff0d804-a0ff-4a7c-9439-b0707dbad554.png)
![Screen Shot 2022-03-14 at 5 08 02 PM](https://user-images.githubusercontent.com/1613739/158269162-03b72827-dfc5-4132-9de6-0b52d52c3df3.png)

for event https://app.bugsnag.com/dealer-inspire/online-shopper-php/errors/622fb8e566649700082f0996?filters[event.since]=30d&filters[error.status]=open&filters[search]=metajob&event_id=622fba460092db705ab40000

### Environment
* Bugsnag version: 2.23.0
* PHP version: 8.1
* Composer version: 2.2.6
* Laravel version: 8.83.0
* Lumen version (if any): none

I noticed this alternate approach in the issues backlog, is using `Tracker` the preferred solution for queue workers? https://github.com/bugsnag/bugsnag-laravel/issues/448  It doesn't appear anywhere in the integration guide.

**Comment by xander-jones** [comment]
Hey @jwadhams, thanks for raising the issue and providing the repro to explain exactly what the issue you're seeing is. Sorry for the delay in getting back to you, we've been having some internal discussions this topic 😄 .

> leaveBreadcrumb seems to correctly isolate data between Laravel queued jobs processed with Horizon workers. I love it, but sometimes, especially with query logging turned on, important breadcrumbs from early in the job appear to be pushed out by later ones.

Breadcrumbs are contextual to the job, so they should be specific to that one process. We've added a roadmap ticket to make the number of breadcrumbs a) configurable, and b) more than 25! We'll keep you posted.

> In BugSnag, the Breadcrumbs never "cross the streams" but the Metadata routinely do. Using merge:true in setMetaData` only means one random status will be set, it doesn't guarantee the right one, because of the delay. (The delay in my real jobs is based on i/o)

Metadata, on the other hand (by comparison to breadcrumbs) is global _when set in the app-level_. You're right, using merge would condense the array down into a single element, and it wouldn't deterministically report the right state because the jobs are async. You could use a [event-scoped callback](https://docs.bugsnag.com/platforms/php/laravel/customizing-error-reports/#adding-callbacks) on errors occuring inside of the job to set metadata.

In any case, I suspect that the increase to breadcrumb numbers would be a satisfactory solution long term anyway?

> I noticed this alternate approach in the issues backlog, is using Tracker the preferred solution for queue workers? https://github.com/bugsnag/bugsnag-laravel/issues/448 It doesn't appear anywhere in the integration guide.

Using the `Tracker` as the linked issue suggests should do what you want. However, it's intended for internal use, hence why it's not documented. This API is not ideal for public use, and so you'd need to merge the existing metadata manually to not lose the automatic metadata Bugsnag records:

```php
/** @var \Illuminate\Queue\QueueManager $queueManager */
$queueManager->before(function (\Illuminate\Queue\Events\JobProcessing $event) {
    $tracker = app(\Bugsnag\BugsnagLaravel\Queue\Tracker::class);
    $tracker->set(
        array_merge(
            $tracker->get(),
            [/* your metadata goes here */]
        )
    )
});
```

**Comment by luke-belton** [comment]
Hi @jwadhams - we've just released https://github.com/bugsnag/bugsnag-laravel/releases/tag/v2.25.0, which [adds](https://github.com/bugsnag/bugsnag-laravel/pull/496) the `max_breadcrumbs` config option 🎉
